#ifndef DIRECTION_CONSTANTS
#define DIRECTION_CONSTANTS

enum AxisDirections { DIRECTION_X = 0, DIRECTION_Y, DIRECTION_Z, NUM_AXIS_DIRECTIONS };

enum FaceDirections { FACE_RIGHT = 1, FACE_LEFT = 2, FACE_UP = 4, FACE_DOWN = 8, FACE_FRONT = 16, FACE_BACK = 32 };

enum CornerDirections {
	CORNER_LBB = 0, CORNER_LBF, CORNER_LTB, CORNER_LTF,
	CORNER_RBB, CORNER_RBF, CORNER_RTB, CORNER_RTF, NUM_CORNER_DIRECTIONS
};

enum PosNegDirection { DIRECTION_NEGATIVE = 0, DIRECTION_POSITIVE, NUM_POS_NEG_DIRECTION };

#endif