# - Try to find fftw3
# Once done this will define
#
#  HDF5_FOUND - system has hdf5
#  HDF5_INCLUDE_DIRS - the hdf5 include directory
#  HDF5_LIBRARIES - Link these to use hdf5

IF( HDF5_INCLUDE_DIRS AND HDF5_LIBRARIES )
    SET( HDF5_FIND_QUIETLY TRUE )
ENDIF()

FIND_PATH( HDF5_INCLUDE_DIRS hdf5.h )
FIND_LIBRARY( HDF5_LIBRARIES NAMES hdf5 )

IF( HDF5_INCLUDE_DIRS AND HDF5_LIBRARIES )
   SET( HDF5_FOUND TRUE )
   INCLUDE( CheckLibraryExists )
   CHECK_LIBRARY_EXISTS( ${HDF5_LIBRARIES} H5Fopen "" HDF5_FOUND )
ELSE()
   SET( HDF5_FOUND FALSE )
ENDIF()

IF( HDF5_FOUND )
  IF( NOT HDF5_FIND_QUIETLY )
    MESSAGE( STATUS "Found HDF5 : ${HDF5_LIBRARIES}" )
  ENDIF( NOT HDF5_FIND_QUIETLY )
ELSE( HDF5_FOUND )
  IF( HDF5_FIND_REQUIRED )
    MESSAGE( FATAL_ERROR "Could NOT find HDF5" )
  ENDIF( HDF5_FIND_REQUIRED)
ENDIF( HDF5_FOUND )

MARK_AS_ADVANCED( HDF5_INCLUDE_DIRS HDF5_LIBRARIES )